services:
  pokeplanner:
    image: ghcr.io/kardam00n/pokeplanner:latest
    container_name: pokeplanner
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
